services:

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: datalens-backend
    ports:
      - "8001:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datalens-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend