import numpy as np
print("====== NumPy Basics =======")
marks=np.array([70,80,82,91,65,88])
print("Marks:",marks)
print("Shape",marks.shape)
print("Size",marks.size)
print("Data Type",marks.dtype)
print("\nFirst Student Marks",marks[0])
print("Last Student Marks",marks[-1])
print("Marks + 5:",marks+5)
print("Marks * 2:",marks*2)
print("\nAverage Marks:",marks.mean())
print("Maximum Marks:",marks.max())
print("Minimum Marks:",marks.min())
print("\nmarks greater than 80:",marks[marks>80])
print("Sum of Marks:",marks.sum())
gpa=np.array([8.88,8.68,8.84,8.94,8.82])
print("\nGPA:",gpa)
print("Maximum GPA:",gpa.max())
print("Minimum GPA:",gpa.min())
print("Average GPA:",gpa.mean())
print("GPA + 0.2:",gpa+0.2)